language: c
compiler: gcc

cache:
  directories:
    - gslib

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - gcc-4.8
            - gfortran-4.8
            - mpich
            - libmpich-dev
      env:
        - MPICH_CC=gcc-4.8

    - os: linux
      addons:
        apt:
          packages:
            - gcc-5
            - gfortran-5
            - mpich
            - libmpich-dev
      env:
        - MPICH_CC=gcc-5

    - os: linux
      addons:
        apt:
          packages:
            - gcc-6
            - gfortran-6
            - mpich
            - libmpich-dev
      env:
        - MPICH_CC=gcc-6

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - sh ./.travis.get_gslib.sh
  - export GSLIBPATH=`pwd`/gslib

script:
  - CC=mpicc make install
  - CC=mpicc make tests
