name: Unit tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run with tmate'
        required: false
        default: false
env:
  MPIEXE: "mpirun --oversubscribe"
  CC: mpicc
jobs:
  graph:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        np: [1, 2, 3, 4]
      fail-fast: false
    env:
      TESTDIR: ${{ github.workspace }}/install/bin
    steps:
      - name: Checkout actions
        uses: actions/checkout@v6
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Install apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y openmpi-bin libopenmpi-dev
          sudo apt install -y build-essential cmake
      - name: Build gslib
        shell: bash
        run: |
          git clone https://github.com/thilinarmtb/gslib.git -b general_graph
          cmake -B ./gslib/build -S ./gslib -DCMAKE_INSTALL_PREFIX=./gslib/install
          cmake --build ./gslib/build --target install
      - name: Build parRSB
        shell: bash
        run: |
          cmake -B build -S . -DCMAKE_INSTALL_PREFIX=./install -Dgs_DIR=./gslib/install/lib/cmake/gs
      - name: Test graph laplacian matrix
        shell: bash
        run: |
          ${MPIEXE} -np ${{ matrix.np }} ${TESTDIR}/parrsb_000_graph_laplacian
      - name: Test graph laplacian operator
        shell: bash
        run: |
          ${MPIEXE} -np ${{ matrix.np }} ${TESTDIR}/parrsb_050_graph_laplacian_op
      - name: Test graph laplacian eigenvalues
        shell: bash
        run: |
          ${MPIEXE} -np ${{ matrix.np }} ${TESTDIR}/parrsb_100_graph_eigenvalues
