name: parRSB CI Tests
on: [push, pull_request]
env:
  GITHUB.TOKEN: ${{ secrets.token }}
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [box_2x2x2, pyramid, tgv, e3q, solid, ethier, vortex, expansion]
        np: [1, 2, 3, 4]
      fail-fast: false
    name: "${{ matrix.test }}, NP = ${{ matrix.np }}"
    env:
      GSVER: 1.0.7
      CC: mpicc
    steps:
      - uses: actions/checkout@v2
      - name: Install apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y mpich libmpich-dev python3-pytest
          sudo apt install -y libblas-dev liblapack-dev
      - name: Build parRSB and clone tests
        shell: bash
        run: |
          # Build gslib
          wget --no-check-certificate -O v$GSVER.tar.gz http://github.com/gslib/gslib/archive/v$GSVER.tar.gz
          mkdir gslib
          tar -zxvf v$GSVER.tar.gz -C ./gslib --strip-components=1
          make -C gslib -j4

          # Build parRSB
          export GSLIBPATH=`pwd`/gslib/build/
          make -j1

          # Clone tests
          git clone https://github.com/thilinarmtb/parRSB-tests.git
      - name: gencon
        shell: bash
        run: |
          export EXAMPLEDIR=`pwd`/build/examples

          cd parRSB-tests/${{ matrix.test }}
          tol=(`cat test.txt | grep tol`); tol=${tol[2]}

          echo "localhost:4" > hostfile

          mpirun -np ${{ matrix.np }} --hostfile hostfile ${EXAMPLEDIR}/gencon \
            --mesh ${{ matrix.test }} --tol=${tol} --no-dump --test
      - name: genmap-lanczos
        shell: bash
        run: |
          export EXAMPLEDIR=`pwd`/build/examples
          export PARRSB_RSB_PRE=0
          export PARRSB_RSB_ALGO=0

          cd parRSB-tests/${{ matrix.test }}
          tol=(`cat test.txt | grep tol`); tol=${tol[2]}

          echo "localhost:4" > hostfile

          mpirun -np ${{ matrix.np }} --hostfile hostfile ${EXAMPLEDIR}/genmap \
            --mesh ${{ matrix.test }} --tol=${tol} --no-dump --test
      - name: genmap-mg
        shell: bash
        run: |
          export EXAMPLEDIR=`pwd`/build/examples
          export PARRSB_RSB_PRE=0
          export PARRSB_RSB_ALGO=1

          cd parRSB-tests/${{ matrix.test }}
          tol=(`cat test.txt | grep tol`); tol=${tol[2]}

          echo "localhost:4" > hostfile

          mpirun -np ${{ matrix.np }} --hostfile hostfile ${EXAMPLEDIR}/genmap \
            --mesh ${{ matrix.test }} --tol=${tol} --no-dump --test
