name: Unit tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  MPIEXE: "mpirun --oversubscribe"
  CC: mpicc
jobs:
  graph:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        np: [1, 2, 3, 4]
      fail-fast: false
    env:
      TESTDIR: ${{ github.workspace }}/build/test
    steps:
      - uses: actions/checkout@v3
      - name: Install apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y openmpi-bin libopenmpi-dev
          sudo apt install -y build-essential cmake
      - name: Build parRSB and clone tests
        shell: bash
        run: |
          # Build gslib
          git clone https://github.com/Nek5000/gslib.git
          make -C gslib -j4

          # Build parRSB
          export GSLIB_DIR=`pwd`/gslib/build/
          make -j4 test
      - name: Test graph laplacian matrix
        shell: bash
        run: |
          cd ${TESTDIR}
          ${MPIEXE} -np ${{ matrix.np }} ./parrsb_000_graph_laplacian
      - name: Test graph laplacian operator
        shell: bash
        run: |
          cd ${TESTDIR}
          ${MPIEXE} -np ${{ matrix.np }} ./parrsb_050_graph_laplacian_op
      - name: Test graph laplacian eigenvalues
        shell: bash
        run: |
          cd ${TESTDIR}
          ${MPIEXE} -np ${{ matrix.np }} ./parrsb_100_graph_eigenvalues
